### ISSUE TITLE
Attribute dump

### ISSUE THREAD

**Issue by yukinagatosc2** [pearxteam/craftdumper#2]
This might be hard because attributes aren't registered the same way say a lot of other things are but being able to dump attributes is something no mod currently does to my knowledge and it would be very useful to a pack maker to know all the attributes that mods in their pack make available all in one place.

**Comment by mrapplexz** [comment]
I've managed to create something like this. The `attributes` dumper will be included in the next update.
![image](https://user-images.githubusercontent.com/7630912/71764188-4dcfe180-2f06-11ea-91f2-8192182244c4.png)

**Comment by mrapplexz** [comment]
Check out the 1.2.0 update on CurseForge.

**Comment by yukinagatosc2** [comment]
ooooo
