### ISSUE TITLE
Armor dump

### ISSUE THREAD

**Issue by floral-qua-floral** [pearxteam/craftdumper#3]
It'd be really handy to get the option to dump all items that can be equipped as armor. Ideally, maybe four or five lists would be best - all items equippable as helmets, as chestplates, as leggings, as boots, and maybe just in any slot.
For the sake of thoroughness, Bauble slot dumps might also be helpful to some people, but armor is probably a higher priority.

**Comment by mrapplexz** [comment]
I'll add an option to dump all the armor as a single table in the next update. You can filter the table by `Slot` column to get, for instance, all the items equippable as helmets.
